# Generated by Django 5.1 on 2025-05-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverification',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='code',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
