# Generated by Django 5.1 on 2025-05-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_emailverification_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_number', models.PositiveSmallIntegerField(unique=True)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
            ],
        ),
    ]
