# Generated by Django 5.1 on 2025-05-04 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_qrcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QRCode',
        ),
    ]
