# Generated by Django 5.1 on 2025-05-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_qrcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_number', models.PositiveSmallIntegerField(unique=True)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='current_department',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
