# Generated by Django 5.1 on 2025-05-08 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_qrcode_patient_current_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QRCode',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='current_department',
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='accounts.doctor'),
        ),
    ]
