# Generated by Django 5.1 on 2025-05-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_treatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
