# Generated by Django 5.1 on 2025-05-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_treatment_qr_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='qr_code_value',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
