# Generated by Django 5.1 on 2025-05-18 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_treatment_qr_code_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='qr_code_value',
        ),
    ]
