# Generated by Django 5.1 on 2025-05-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_treatment_qr_code_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='scanned_data',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
