# Generated by Django 5.1 on 2025-05-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_treatment_scanned_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='scanned_data',
        ),
        migrations.AddField(
            model_name='treatment',
            name='scanned_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
