# Generated by Django 5.1 on 2025-05-18 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_treatment_scanned_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='qr_code_value',
        ),
    ]
