# Generated by Django 5.1 on 2025-08-27 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_treatment_qr_code_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_treatment', to='accounts.patient'),
        ),
        migrations.CreateModel(
            name='PatientTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_treatment', to='accounts.patient')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='treatment_steps/')),
                ('duration_days', models.PositiveIntegerField()),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='accounts.patienttreatment')),
            ],
        ),
    ]
