# Generated by Django 5.1 on 2025-08-27 12:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_treatment_patient_patienttreatment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentstep',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
