# Generated by Django 5.1 on 2025-08-31 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_treatmentstepphoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treatmentstep',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='treatmentstep',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='treatmentstep',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='treatmentstep',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='treatmentstep',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
