# Generated by Django 5.1 on 2025-08-31 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_treatmentstep_options_treatmentstep_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='patient_reports/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('report_period_start', models.DateField(blank=True, null=True)),
                ('report_period_end', models.DateField(blank=True, null=True)),
                ('title', models.CharField(default='Treatment Progress Report', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Admin notes about this report')),
                ('is_active', models.BooleanField(default=True, help_text='Set to False to hide from doctors')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='accounts.patient')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
