# Generated by Django 5.1 on 2025-08-31 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_patientreport'),
    ]

    operations = [
    ]
