# Generated by Django 5.1 on 2025-09-12 09:10

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20250831_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientreport',
            name='report_file',
            field=models.FileField(blank=True, help_text='PDF report file (stored locally, not on ImgBB)', null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='patient_reports/'),
        ),
    ]
