# Generated by Django 5.1 on 2025-09-12 09:19

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_fix_report_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientreport',
            name='original_filename',
            field=models.CharField(blank=True, help_text='Original PDF filename', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientreport',
            name='report_data',
            field=models.BinaryField(blank=True, help_text='PDF file stored as binary data', null=True),
        ),
        migrations.AlterField(
            model_name='patientreport',
            name='report_file',
            field=models.FileField(blank=True, help_text='PDF file (will be converted to binary storage)', null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='patient_reports/'),
        ),
    ]
