# Generated by Django 5.1 on 2025-09-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_patientreport_original_filename_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientreport',
            name='original_filename',
        ),
        migrations.RemoveField(
            model_name='patientreport',
            name='report_data',
        ),
        migrations.AddField(
            model_name='treatment',
            name='qr_image_url',
            field=models.URLField(blank=True, help_text='Permanent ImgBB URL for the QR image', null=True),
        ),
        migrations.AddField(
            model_name='treatmentstep',
            name='image_url',
            field=models.URLField(blank=True, help_text='Permanent ImgBB URL for the step image', null=True),
        ),
        migrations.AddField(
            model_name='treatmentstepphoto',
            name='image_url',
            field=models.URLField(blank=True, help_text='Permanent ImgBB URL for the photo', null=True),
        ),
        migrations.AlterField(
            model_name='patientreport',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='patient_reports/'),
        ),
    ]
