# Generated by Django 5.1 on 2025-09-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_remove_patientreport_original_filename_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientreport',
            name='report_file',
        ),
        migrations.AddField(
            model_name='patientreport',
            name='report_file_url',
            field=models.URLField(blank=True, help_text='Box.com shareable link to the PDF report', null=True),
        ),
    ]
