# Generated by Django 5.1 on 2025-09-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_remove_patientreport_report_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientreport',
            name='report_file_url',
        ),
        migrations.AddField(
            model_name='patientreport',
            name='report_file',
            field=models.FileField(blank=True, help_text='Doctor report PDF file (stored in /var/media/pdf_reports)', null=True, upload_to='pdf_reports/'),
        ),
    ]
