# Generated by Django 5.1 on 2025-09-17 09:32

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_remove_patientreport_report_file_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientreport',
            name='report_file',
            field=models.FileField(blank=True, help_text='Doctor report PDF file (stored in /var/media/pdf_reports)', null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location='/var/media'), upload_to='pdf_reports/'),
        ),
    ]
